apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gpu-check-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.6, pipelines.kubeflow.org/pipeline_compilation_time: '2021-07-31T15:15:38.268840',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "gpu_check_pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.6}
spec:
  entrypoint: gpu-check-pipeline
  templates:
  - name: gpu-check-pipeline
    dag:
      tasks:
      - {name: hello-world-gpu, template: hello-world-gpu}
  - name: hello-world-gpu
    container:
      args: []
      command: [sh, -c, nvidia-smi]
      image: tensorflow/tensorflow:2.4.2-gpu
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.6.6
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Prints
          if GPU is available", "implementation": {"container": {"command": ["sh",
          "-c", "nvidia-smi"], "image": "tensorflow/tensorflow:2.4.2-gpu"}}, "name":
          "Hello World GPU"}', pipelines.kubeflow.org/component_ref: '{"digest": "4ec63a59e83edb3480661a061ccf87a0ad9d65e22c01a42e33f6e970666c8ce2",
          "url": "./hello-world-gpu.yaml"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
